title: Halloween Ahoy!
description: Dedicated to the holiday that's not a holiday at all known as Halloween. Trick arrr treat.
author:
  name: Halloween Ahoy!
  email: halloweenahoy@gmail.com
url: "https://halloweenahoy.com" # the base hostname & protocol for your site
enforce_ssl: "halloweenahoy.com"
permalink: /:title/
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
