title: Halloween Ahoy!
description: Dedicated to the holiday that's not a holiday at all known as Halloween. Trick arrr treat.
author:
  name: Halloween Ahoy!
  email: halloweenahoy@gmail.com
permalink: /:title/
markdown: kramdown
talkyard_server_url: https://comments-for-halloweenahoy-com.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
