title: Halloween Ahoy!
description: This here be a Halloween blog. Trick arrr treat!.
author:
  name: Halloween Ahoy!
  email: halloweenahoy@gmail.com
facebook_url: 
twitter_url: https://twitter.com/halloweenahoy
pinterest_url:
instagram_url: https://www.instagram.com/halloweenahoy/
permalink: /:title/
markdown: kramdown
talkyard_server_url: https://comments-for-halloweenahoy-com.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
